# Generated by Django 5.0.7 on 2024-07-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_address_line1_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
